### ISSUE TITLE
Too many settings requirements

### ISSUE THREAD

**Issue by iBasit** [catamphetamine/react-time-ago#4]
Getting started with this, requires too many configuration and I'm not even sure where to set configuration because I keep getting error "cant resolve javascript-time-ago" after installing react-time-go.

**Comment by catamphetamine** [comment]
Define "too many configuration".

`javascript-time-ago` should have installed along `react-time-ago`.
If not, install `javascript-time-ago` manually.

**Comment by iBasit** [comment]
yep did them both. still got above error. 

Sorry, I don't mean to be rude, but I think there should be default configuration "en" and user can change the settings, if they wanted to.  Like other scripts.

**Comment by catamphetamine** [comment]
It's impossible: if you did them both then it can't be not found.

You're not being rude, it doesn't bundle any locale by default on purpose - because it's international.

**Comment by catamphetamine** [comment]
By the way, perhaps you meant this error

> ERROR in ./src/index.js
Module not found: Error: Can't resolve 'javascript-time-ago/locales/en' in 'c:\dev\webpack-react-redux-isomorphic-render-example\src'

In which case it should be `import en from 'javascript-time-ago/locale/en'` instead of `import en from 'javascript-time-ago/locale**s**/en'`
